In [ ]:
import pandas as pd
import numpy
from IPython.display import HTML, display
from sklearn import feature_selection
import zhishu
import common

# 只取10年前的数据
from_date = "2016-01-14"
data_dir = "data-指数-260114"

pd.set_option("display.max_columns", None,
              "display.float_format",lambda x : '%.4f' % x)

# 宽基
zhishu_list = [
    "SH000016-上证50",
    "SH000300-沪深300",
    "SZ399006-创业板指",
    "SH000510-中证A500",
]
kuanji_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("宽基 - 维度-价格 相关系数")
display(kuanji_df)

# 证券金融
zhishu_list = [
    "SZ399986-中证银行",
    "SZ399975-证券公司",
    "SZ399437-证券龙头",
]
jinrong_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("证券金融 - 维度-价格 相关系数")
display(jinrong_df)


# 消费民生
zhishu_list = [
    "SH000932-中证消费",
    # 'CSIH30533_中国互联网50',
    "SZ399989-中证医疗",
    "CSI930726-中证生物医药",
    "CSI930641-中证中药",
    "CSI931152-创新药",
]
minsheng_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("消费民生 - 维度-价格 相关系数")
display(minsheng_df)

# 新科技
zhishu_list = [
    'CSI930713-人工智能',
    'CSI000941-新能源',
    'CSIH30184-半导体',
    'SZ399976-CS新能源车',
    'CSIH30590-机器人',
    'CSI931798-光伏龙头',
    'CSI931151-光伏产业'
]
tech_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("新科技 - 维度-价格 相关系数")
display(tech_df)

# 基础工业
zhishu_list = [
    "CSI931866-中证机床",
    "SH000928-中证能源",
    "SZ399440-国证钢铁",
    "CSI930632-CS稀金属",
    "SH000819-有色金属",
    "CSIH30199-电力指数",
]
industry_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("基础工业 - 维度-价格 相关系数")
display(industry_df)

# 国防军工
zhishu_list = [
    "SZ399967-中证军工", 
    "CSI931066-军工龙头",
]
military_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("国防军工 - 维度-价格 相关系数")
display(military_df)

# 夕阳
zhishu_list = [
    'CSI931009-建筑材料',
    'SZ399995-基建工程',
]
hopeless_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("夕阳产业 - 维度-价格 相关系数")
display(hopeless_df)

KeyboardInterrupt:

In [ ]:
kuanji_dim_df = common.get_highest_correlation_dim(kuanji_df)
common.print_title("宽基 - 最相关系数")
display(kuanji_dim_df)

jinrong_dim_df = common.get_highest_correlation_dim(jinrong_df)
common.print_title("证券金融 - 最相关系数")
display(jinrong_dim_df)

mingsheng_dim_df = common.get_highest_correlation_dim(minsheng_df)
common.print_title("消费民生 - 最相关系数")
display(mingsheng_dim_df)

tech_dim_df = common.get_highest_correlation_dim(tech_df)
common.print_title("新科技 - 最相关系数")
display(tech_dim_df)

industry_dim_df = common.get_highest_correlation_dim(industry_df)
common.print_title("基础工业 - 最相关系数")
display(industry_dim_df)

military_dim_df = common.get_highest_correlation_dim(military_df)
common.print_title("国防军工 - 最相关系数")
display(military_dim_df)

hopless_dim_df = common.get_highest_correlation_dim(hopeless_df)
common.print_title("夕阳产业 - 最相关系数")
display(hopless_dim_df)

                    最相关维度   相关系数      最早数据日期
SH000016-上证50    PE_ETF加权 0.7739  2016-01-14
SH000300-沪深300   PE_ETF加权 0.7723  2016-01-14
SZ399006-创业板指    PB_ETF加权 0.8421  2016-01-14
SH000510-中证A500  PB_ETF加权 0.9866  2024-09-24

                 最相关维度   相关系数      最早数据日期
SZ399986-中证银行  PE_市值加权 0.7999  2016-01-14
SZ399975-证券公司  PB_市值加权 0.8362  2016-01-14
SZ399437-证券龙头  PB_市值加权 0.7948  2016-01-14

                     最相关维度   相关系数      最早数据日期
SH000932-中证消费     PB_ETF加权 0.8838  2016-01-14
SZ399989-中证医疗      PB_市值加权 0.9002  2016-01-14
CSI930726-中证生物医药   PB_市值加权 0.8486  2016-01-14

                    最相关维度   相关系数      最早数据日期
CSI930713-人工智能   PB_ETF加权 0.8986  2016-01-14
CSI000941-新能源     PB_市值加权 0.9363  2016-01-14
CSIH30184-半导体    PB_ETF加权 0.8737  2016-01-14
SZ399976-CS新能源车  PB_ETF加权 0.8122  2016-01-14
CSIH30590-机器人    PB_ETF加权 0.9283  2016-01-14
CSI931798-光伏龙头      PB_等权 0.6910  2017-01-03
CSI931151-光伏产业    PB_市值加权 0.9631  2019-04-23

                    最相关维度   相关系数      最早数据日期
CSI931866-中证机床    PE_市值加权 0.9714  2022-05-10
SH000928-中证能源       ROE % 0.7618  2016-01-14
SZ399440-国证钢铁     PB_市值加权 0.9391  2016-01-14
CSI930632-CS稀金属   PB_市值加权 0.6070  2016-01-14
SH000819-有色金属     PB_市值加权 0.8290  2016-01-14
CSIH30199-电力指数   PB_ETF加权 0.7829  2016-01-14

                  最相关维度   相关系数      最早数据日期
SZ399967-中证军工   PB_市值加权 0.8375  2016-01-14
CSI931066-军工龙头    PB_等权 0.8627  2018-02-05

                  最相关维度   相关系数      最早数据日期
CSI931009-建筑材料  PB_市值加权 0.7489  2016-01-14
SZ399995-基建工程   PE_市值加权 0.9671  2016-01-14

In [ ]:
common.print_title("宽基 - 最相关维度百分位%")
display(common.calc_highest_correlation_dim_latest_percentile(
    data_dir, kuanji_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("证券金融 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, jinrong_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("消费民生 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, mingsheng_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("新科技 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, tech_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("基础工业 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, industry_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("国防军工 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, military_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("夕阳产业 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, hopless_dim_df, from_date, date_col_name="日期"
    )
)

                    最相关维度   相关系数      最早数据日期   最新维度值  最新百分位%      最新数据日期
SH000016-上证50    PE_ETF加权 0.7739  2016-01-14 12.6200 91.2273  2026-01-13
SH000300-沪深300   PE_ETF加权 0.7723  2016-01-14 16.0500 88.3443  2026-01-13
SZ399006-创业板指    PB_ETF加权 0.8421  2016-01-14  5.9400 70.2391  2026-01-13
SH000510-中证A500  PB_ETF加权 0.9866  2024-09-24  1.7100 99.6835  2026-01-13

                 最相关维度   相关系数      最早数据日期  最新维度值  最新百分位%      最新数据日期
SZ399986-中证银行  PE_市值加权 0.7999  2016-01-14 7.1400 93.0705  2026-01-13
SZ399975-证券公司  PB_市值加权 0.8362  2016-01-14 1.3500 38.3216  2026-01-26
SZ399437-证券龙头  PB_市值加权 0.7948  2016-01-14 1.3300 37.9909  2026-01-26

                     最相关维度   相关系数      最早数据日期  最新维度值  最新百分位%      最新数据日期
SH000932-中证消费     PB_ETF加权 0.8838  2016-01-14 4.1400 12.6030  2026-01-13
SZ399989-中证医疗      PB_市值加权 0.9002  2016-01-14 3.8000 16.8880  2026-01-13
CSI930726-中证生物医药   PB_市值加权 0.8486  2016-01-14 4.9200 26.8946  2026-01-13

                    最相关维度   相关系数      最早数据日期  最新维度值  最新百分位%      最新数据日期
CSI930713-人工智能   PB_ETF加权 0.8986  2016-01-14 7.8600 99.9585  2026-01-13
CSI000941-新能源     PB_市值加权 0.9363  2016-01-14 3.3700 76.1503  2026-01-13
CSIH30184-半导体    PB_ETF加权 0.8737  2016-01-14 8.2100 89.5387  2026-01-13
SZ399976-CS新能源车  PB_ETF加权 0.8122  2016-01-14 3.8900 47.6524  2026-02-06
CSIH30590-机器人    PB_ETF加权 0.9283  2016-01-14 5.0400 93.6541  2026-01-13
CSI931798-光伏龙头      PB_等权 0.6910  2017-01-03 3.2300 38.9869  2026-02-06
CSI931151-光伏产业    PB_市值加权 0.9631  2019-04-23 2.6600 52.8770  2026-02-06

                    最相关维度   相关系数      最早数据日期   最新维度值  最新百分位%      最新数据日期
CSI931866-中证机床    PE_市值加权 0.9714  2022-05-10 66.2600 98.5777  2026-02-06
SH000928-中证能源       ROE % 0.7618  2016-01-14 10.0700 63.2619  2026-01-13
SZ399440-国证钢铁     PB_市值加权 0.9391  2016-01-14  1.1900 68.2158  2026-01-13
CSI930632-CS稀金属   PB_市值加权 0.6070  2016-01-14  4.3100 74.6163  2026-01-13
SH000819-有色金属     PB_市值加权 0.8290  2016-01-14  4.0300 99.2946  2026-01-13
CSIH30199-电力指数   PB_ETF加权 0.7829  2016-01-14  1.5100 42.9282  2026-01-13

                  最相关维度   相关系数      最早数据日期  最新维度值  最新百分位%      最新数据日期
SZ399967-中证军工   PB_市值加权 0.8375  2016-01-14 4.5300 97.2817  2026-01-13
CSI931066-军工龙头    PB_等权 0.8627  2018-02-05 3.7700 63.3023  2026-01-22

                  最相关维度   相关系数      最早数据日期  最新维度值  最新百分位%      最新数据日期
CSI931009-建筑材料  PB_市值加权 0.7489  2016-01-14 0.9900 20.5809  2026-01-13
SZ399995-基建工程   PE_市值加权 0.9671  2016-01-14 9.1700 65.4036  2026-01-13