In [1]:
import pandas as pd
import numpy
from IPython.display import HTML, display
from sklearn import feature_selection
import zhishu
import common

# 只取10年前的数据
from_date = "2016-01-14"
data_dir = "data-指数-260801"

pd.set_option("display.max_columns", None,
              "display.float_format",lambda x : '%.4f' % x)

# 宽基
zhishu_list = [
    "SH000016-上证50",
    "SH000300-沪深300",
    "SZ399006-创业板指",
    "SZ399006-创业板指",
    "SH000688-科创50",
]
kuanji_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("宽基 - 维度-价格 相关系数")
display(kuanji_df)

# 证券金融
zhishu_list = [
    "SZ399986-中证银行",
    "SZ399975-证券公司",
    "SZ399437-证券龙头",
]
jinrong_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("证券金融 - 维度-价格 相关系数")
display(jinrong_df)


# 消费民生
zhishu_list = [
    "SH000932-中证消费",
    # 'CSIH30533_中国互联网50',
    "SZ399989-中证医疗",
    "CSI930726-中证生物医药",
    "CSI930641-中证中药",
    "CSI931152-创新药",
    "SH000913-300医药",
    "SH000933-中证医药"
]
minsheng_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("消费民生 - 维度-价格 相关系数")
display(minsheng_df)

# 新科技
zhishu_list = [
    'CSI930713-人工智能',
    'CSI000941-新能源',
    'CSIH30184-半导体',
    'SZ399976-CS新能源车',
    'CSIH30590-机器人',
    # 'CSI931798-光伏龙头',
    'CSI931151-光伏产业',
    'CSI931160-通信设备',
]
tech_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("新科技 - 维度-价格 相关系数")
display(tech_df)

# 基础工业
zhishu_list = [
    # "CSI931866-中证机床",
    "SH000928-中证能源",
    "SZ399440-国证钢铁",
    "CSI930632-CS稀金属",
    "SH000819-有色金属",
    "CSIH30199-电力指数",
    "SZ399998-中证煤炭",
]
industry_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("基础工业 - 维度-价格 相关系数")
display(industry_df)

# 国防军工
zhishu_list = [
    "SZ399967-中证军工", 
    "CSI931066-军工龙头",
]
military_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("国防军工 - 维度-价格 相关系数")
display(military_df)

# 夕阳
zhishu_list = [
    # 'CSI931009-建筑材料',
    # 'SZ399995-基建工程',
]
hopeless_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("夕阳产业 - 维度-价格 相关系数")
display(hopeless_df)

,PE_ETF加权,PE_市值加权,PE_等权,PB_ETF加权,PB_市值加权,PB_等权,股息收益率 %,ROE %,最早数据日期
SH000016-上证50,0.7780,0.7286,0.5715,0.6772,0.6345,0.4819,-0.5826,-0.2970,2016-01-14
SH000300-沪深300,0.7880,0.7607,0.4940,0.6092,0.4359,0.5519,-0.4599,-0.4179,2016-01-14
SZ399006-创业板指,0.3658,0.5036,0.5160,0.7896,0.7099,0.5621,-0.1898,0.5418,2016-01-14
SZ399006-创业板指,0.3658,0.5036,0.5160,0.7896,0.7099,0.5621,-0.1898,0.5418,2016-01-14
SH000688-科创50,0.6304,0.6799,0.8907,0.9496,0.9759,0.7421,-0.8355,-0.2578,2020-07-23

,PE_ETF加权,PE_市值加权,PE_等权,PB_ETF加权,PB_市值加权,PB_等权,股息收益率 %,ROE %,最早数据日期
SZ399986-中证银行,0.6597,0.8137,0.4091,0.0182,0.0948,-0.0828,-0.3932,-0.4862,2016-01-14
SZ399975-证券公司,0.1340,0.1459,0.0367,0.7889,0.8073,0.6703,-0.2384,0.4252,2016-01-14
SZ399437-证券龙头,0.1186,0.1636,-0.0211,0.6795,0.7505,0.5004,-0.2936,0.3670,2016-01-14

,PE_ETF加权,PE_市值加权,PE_等权,PB_ETF加权,PB_市值加权,PB_等权,股息收益率 %,ROE %,最早数据日期
SH000932-中证消费,0.6650,0.6415,0.5763,0.8752,0.8490,0.5456,-0.3129,0.4015,2016-01-14
SZ399989-中证医疗,0.2747,0.3375,0.4550,0.8965,0.9029,0.7726,-0.4728,0.6895,2016-01-14
CSI930726-中证生物医药,0.4656,0.5627,0.3189,0.7449,0.8528,0.3817,-0.4987,0.3448,2016-01-14
CSI930641-中证中药,0.4044,0.5491,0.5284,0.6557,0.6360,0.6291,-0.4686,0.1769,2016-01-14
CSI931152-创新药,0.8625,0.5822,0.8708,0.9093,0.9239,0.6948,-0.8400,0.6911,2019-04-23
SH000913-300医药,0.8980,0.9037,0.8227,0.9274,0.9231,0.7546,-0.6515,0.2402,2016-01-14
SH000933-中证医药,0.7506,0.7378,0.6282,0.9135,0.9213,0.6818,-0.6985,0.4563,2016-01-14

,PE_ETF加权,PE_市值加权,PE_等权,PB_ETF加权,PB_市值加权,PB_等权,股息收益率 %,ROE %,最早数据日期
CSI930713-人工智能,0.3703,0.5352,0.2398,0.9314,0.8899,0.5305,-0.3539,0.4055,2016-01-14
CSI000941-新能源,0.2681,0.4696,0.1181,0.9179,0.9281,0.8960,-0.4428,0.5469,2016-01-14
CSIH30184-半导体,0.0659,0.6710,0.6291,0.8671,0.8156,0.7365,-0.6312,0.2525,2016-01-14
SZ399976-CS新能源车,0.2764,0.3896,0.4351,0.7693,0.7607,0.5581,-0.4327,0.0995,2016-01-14
CSIH30590-机器人,0.3728,0.6020,0.6506,0.9108,0.9010,0.7677,-0.6614,0.1534,2016-01-14
CSI931151-光伏产业,0.0418,0.1002,0.4021,0.9491,0.9563,0.9245,-0.5868,0.4520,2019-04-23
CSI931160-通信设备,-0.0064,0.2869,0.6798,0.9463,0.9517,0.7481,-0.1258,0.4448,2016-01-14

,PE_ETF加权,PE_市值加权,PE_等权,PB_ETF加权,PB_市值加权,PB_等权,股息收益率 %,ROE %,最早数据日期
SH000928-中证能源,-0.2011,-0.2952,-0.1671,0.6628,0.7418,0.2765,0.3696,0.7094,2016-01-14
SZ399440-国证钢铁,-0.1569,-0.1481,0.1224,0.8986,0.9368,0.5782,-0.5360,0.1831,2016-01-14
CSI930632-CS稀金属,0.0224,0.0387,-0.3049,0.5077,0.5793,0.3163,-0.2591,0.4544,2016-01-14
SH000819-有色金属,-0.1943,-0.0884,-0.2054,0.7729,0.8577,0.5022,0.0546,0.4945,2016-01-14
CSIH30199-电力指数,0.1085,0.1588,0.1031,0.7333,0.6317,0.3630,-0.3852,0.0707,2016-01-14
SZ399998-中证煤炭,-0.0573,-0.1606,-0.1790,0.9082,0.9019,0.2298,0.4097,0.4818,2016-01-14

,PE_ETF加权,PE_市值加权,PE_等权,PB_ETF加权,PB_市值加权,PB_等权,股息收益率 %,ROE %,最早数据日期
SZ399967-中证军工,0.1741,0.3502,0.4716,0.8227,0.8348,0.6787,0.0101,0.2147,2016-01-14
CSI931066-军工龙头,0.5214,0.4745,0.3271,0.8295,0.8251,0.8295,-0.7117,0.1494,2018-02-05

Empty DataFrame
Columns: [PE_ETF加权, PE_市值加权, PE_等权, PB_ETF加权, PB_市值加权, PB_等权, 股息收益率 %, ROE %, 最早数据日期]
Index: []

In [2]:
kuanji_dim_df = common.get_highest_correlation_dim(kuanji_df)
common.print_title("宽基 - 最相关系数")
display(kuanji_dim_df)

jinrong_dim_df = common.get_highest_correlation_dim(jinrong_df)
common.print_title("证券金融 - 最相关系数")
display(jinrong_dim_df)

mingsheng_dim_df = common.get_highest_correlation_dim(minsheng_df)
common.print_title("消费民生 - 最相关系数")
display(mingsheng_dim_df)

tech_dim_df = common.get_highest_correlation_dim(tech_df)
common.print_title("新科技 - 最相关系数")
display(tech_dim_df)

industry_dim_df = common.get_highest_correlation_dim(industry_df)
common.print_title("基础工业 - 最相关系数")
display(industry_dim_df)

military_dim_df = common.get_highest_correlation_dim(military_df)
common.print_title("国防军工 - 最相关系数")
display(military_dim_df)

hopless_dim_df = common.get_highest_correlation_dim(hopeless_df)
common.print_title("夕阳产业 - 最相关系数")
display(hopless_dim_df)

,最相关维度,相关系数,最早数据日期
SH000016-上证50,PE_ETF加权,0.7780,2016-01-14
SH000300-沪深300,PE_ETF加权,0.7880,2016-01-14
SZ399006-创业板指,PB_ETF加权,SZ399006-创业板指 0.7896 SZ399006-创业板指 0.7896 ...,2016-01-14
SZ399006-创业板指,PB_ETF加权,SZ399006-创业板指 0.7896 SZ399006-创业板指 0.7896 ...,2016-01-14
SH000688-科创50,PB_市值加权,0.9759,2020-07-23

                 最相关维度   相关系数      最早数据日期
SZ399986-中证银行  PE_市值加权 0.8137  2016-01-14
SZ399975-证券公司  PB_市值加权 0.8073  2016-01-14
SZ399437-证券龙头  PB_市值加权 0.7505  2016-01-14

                     最相关维度   相关系数      最早数据日期
SH000932-中证消费     PB_ETF加权 0.8752  2016-01-14
SZ399989-中证医疗      PB_市值加权 0.9029  2016-01-14
CSI930726-中证生物医药   PB_市值加权 0.8528  2016-01-14
CSI930641-中证中药    PB_ETF加权 0.6557  2016-01-14
CSI931152-创新药      PB_市值加权 0.9239  2019-04-23
SH000913-300医药    PB_ETF加权 0.9274  2016-01-14
SH000933-中证医药      PB_市值加权 0.9213  2016-01-14

                    最相关维度   相关系数      最早数据日期
CSI930713-人工智能   PB_ETF加权 0.9314  2016-01-14
CSI000941-新能源     PB_市值加权 0.9281  2016-01-14
CSIH30184-半导体    PB_ETF加权 0.8671  2016-01-14
SZ399976-CS新能源车  PB_ETF加权 0.7693  2016-01-14
CSIH30590-机器人    PB_ETF加权 0.9108  2016-01-14
CSI931151-光伏产业    PB_市值加权 0.9563  2019-04-23
CSI931160-通信设备    PB_市值加权 0.9517  2016-01-14

                    最相关维度   相关系数      最早数据日期
SH000928-中证能源     PB_市值加权 0.7418  2016-01-14
SZ399440-国证钢铁     PB_市值加权 0.9368  2016-01-14
CSI930632-CS稀金属   PB_市值加权 0.5793  2016-01-14
SH000819-有色金属     PB_市值加权 0.8577  2016-01-14
CSIH30199-电力指数   PB_ETF加权 0.7333  2016-01-14
SZ399998-中证煤炭    PB_ETF加权 0.9082  2016-01-14

                  最相关维度   相关系数      最早数据日期
SZ399967-中证军工   PB_市值加权 0.8348  2016-01-14
CSI931066-军工龙头    PB_等权 0.8295  2018-02-05

Empty DataFrame
Columns: [最相关维度, 相关系数, 最早数据日期]
Index: []

In [3]:
common.print_title("宽基 - 最相关维度百分位%")
display(common.calc_highest_correlation_dim_latest_percentile(
    data_dir, kuanji_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("证券金融 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, jinrong_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("消费民生 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, mingsheng_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("新科技 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, tech_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("基础工业 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, industry_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("国防军工 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, military_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("夕阳产业 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, hopless_dim_df, from_date, date_col_name="日期"
    )
)

,最相关维度,相关系数,最早数据日期,最新维度值,最新百分位%,最新数据日期
SH000016-上证50,PE_ETF加权,0.7780,2016-01-14,12.2300,86.9531,2026-07-31
SH000300-沪深300,PE_ETF加权,0.7880,2016-01-14,15.8800,84.7656,2026-07-31
SZ399006-创业板指,PB_ETF加权,SZ399006-创业板指 0.7896 SZ399006-创业板指 0.7896 ...,2016-01-14,5.9300,68.0610,2026-07-31
SZ399006-创业板指,PB_ETF加权,SZ399006-创业板指 0.7896 SZ399006-创业板指 0.7896 ...,2016-01-14,5.9300,68.0610,2026-07-31
SH000688-科创50,PB_市值加权,0.9759,2020-07-23,8.1300,97.2621,2026-07-31

                 最相关维度   相关系数      最早数据日期  最新维度值  最新百分位%      最新数据日期
SZ399986-中证银行  PE_市值加权 0.8137  2016-01-14 7.2000 94.5319  2026-07-31
SZ399975-证券公司  PB_市值加权 0.8073  2016-01-14 1.1600 14.8308  2026-07-31
SZ399437-证券龙头  PB_市值加权 0.7505  2016-01-14 1.1500 15.8930  2026-07-31

                     最相关维度   相关系数      最早数据日期  最新维度值  最新百分位%      最新数据日期
SH000932-中证消费     PB_ETF加权 0.8752  2016-01-14 3.5900  6.4062  2026-07-31
SZ399989-中证医疗      PB_市值加权 0.9029  2016-01-14 3.2500  8.0645  2026-07-31
CSI930726-中证生物医药   PB_市值加权 0.8528  2016-01-14 4.4800 23.5731  2026-07-31
CSI930641-中证中药    PB_ETF加权 0.6557  2016-01-14 2.0500  2.0858  2026-07-31
CSI931152-创新药      PB_市值加权 0.9239  2019-04-23 3.9700 45.9444  2026-07-31
SH000913-300医药    PB_ETF加权 0.9274  2016-01-14 3.4500 11.8359  2026-07-31
SH000933-中证医药      PB_市值加权 0.9213  2016-01-14 3.0900 17.5391  2026-07-31

                    最相关维度   相关系数      最早数据日期  最新维度值  最新百分位%      最新数据日期
CSI930713-人工智能   PB_ETF加权 0.9314  2016-01-14 8.4200 97.8749  2026-07-31
CSI000941-新能源     PB_市值加权 0.9281  2016-01-14 2.8700 54.6619  2026-07-31
CSIH30184-半导体    PB_ETF加权 0.8671  2016-01-14 9.3500 93.1196  2026-07-31
SZ399976-CS新能源车  PB_ETF加权 0.7693  2016-01-14 3.3000 28.0881  2026-07-31
CSIH30590-机器人    PB_ETF加权 0.9108  2016-01-14 4.4600 81.6608  2026-07-31
CSI931151-光伏产业    PB_市值加权 0.9563  2019-04-23 1.8900 23.9932  2026-07-31
CSI931160-通信设备    PB_市值加权 0.9517  2016-01-14 7.8900 97.1853  2026-07-31

                    最相关维度   相关系数      最早数据日期  最新维度值  最新百分位%      最新数据日期
SH000928-中证能源     PB_市值加权 0.7418  2016-01-14 1.4000 92.2266  2026-07-31
SZ399440-国证钢铁     PB_市值加权 0.9368  2016-01-14 0.9400 32.0220  2026-07-31
CSI930632-CS稀金属   PB_市值加权 0.5793  2016-01-14 3.5200 48.1307  2026-07-31
SH000819-有色金属     PB_市值加权 0.8577  2016-01-14 3.2600 86.8214  2026-07-31
CSIH30199-电力指数   PB_ETF加权 0.7333  2016-01-14 1.5600 58.2841  2026-07-31
SZ399998-中证煤炭    PB_ETF加权 0.9082  2016-01-14 1.6200 90.9375  2026-07-31

                  最相关维度   相关系数      最早数据日期  最新维度值  最新百分位%      最新数据日期
SZ399967-中证军工   PB_市值加权 0.8348  2016-01-14 3.1600 45.3516  2026-07-31
CSI931066-军工龙头    PB_等权 0.8295  2018-02-05 2.6200  3.5036  2026-07-31

Empty DataFrame
Columns: [最相关维度, 相关系数, 最早数据日期, 最新维度值, 最新百分位%, 最新数据日期]
Index: []