In [5]:
import pandas as pd
import numpy
from IPython.display import HTML, display
from sklearn import feature_selection
import zhishu
import common

# 只取10年前的数据
from_date = "2016-01-14"
data_dir = "data-指数-261030"

pd.set_option("display.max_columns", None,
              "display.float_format",lambda x : '%.4f' % x)

# 宽基
zhishu_list = [
    "SH000016-上证50",
    "SH000300-沪深300",
    "SZ399006-创业板指",
    "SH000688-科创50",
    "SH000510-中证A500",
]
kuanji_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("宽基 - 维度-价格 相关系数")
display(kuanji_df)

# 证券金融
zhishu_list = [
    "SZ399986-中证银行",
    "SZ399975-证券公司",
    "SZ399437-证券龙头",
]
jinrong_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("证券金融 - 维度-价格 相关系数")
display(jinrong_df)


# 消费民生
zhishu_list = [
    "SH000932-中证消费",
    # 'CSIH30533_中国互联网50',
    "SZ399989-中证医疗",
    "CSI930726-中证生物医药",
    "CSI930641-中证中药",
    "CSI931152-创新药",
    "SH000913-300医药",
    "SH000933-中证医药"
]
minsheng_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("消费民生 - 维度-价格 相关系数")
display(minsheng_df)

# 新科技
zhishu_list = [
    'CSI930713-人工智能',
    'CSI000941-新能源',
    'CSIH30184-半导体',
    'SZ399976-CS新能源车',
    'CSIH30590-机器人',
    # 'CSI931798-光伏龙头',
    'CSI931151-光伏产业',
    'CSI931160-通信设备',
]
tech_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("新科技 - 维度-价格 相关系数")
display(tech_df)

# 基础工业
zhishu_list = [
    # "CSI931866-中证机床",
    "SH000928-中证能源",
    # "SZ399440-国证钢铁",
    "CSI930632-CS稀金属",
    "SH000819-有色金属",
    "CSIH30199-电力指数",
    # "SZ399998-中证煤炭",
]
industry_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("基础工业 - 维度-价格 相关系数")
display(industry_df)

# 国防军工
zhishu_list = [
    "SZ399967-中证军工", 
    "CSI931066-军工龙头",
]
military_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("国防军工 - 维度-价格 相关系数")
display(military_df)

# 夕阳
zhishu_list = [
    # 'CSI931009-建筑材料',
    # 'SZ399995-基建工程',
]
hopeless_df = zhishu.calc_dim_correlations(data_dir, zhishu_list, from_date)
common.print_title("夕阳产业 - 维度-价格 相关系数")
display(hopeless_df)

,PE_ETF加权,PE_市值加权,PE_等权,PB_ETF加权,PB_市值加权,PB_等权,股息收益率 %,ROE %,最早数据日期
SH000016-上证50,0.7898,0.7290,0.5722,0.6913,0.6314,0.4829,-0.5825,-0.3002,2016-01-14
SH000300-沪深300,0.8101,0.7633,0.4682,0.6259,0.4256,0.5366,-0.4509,-0.4305,2016-01-14
SZ399006-创业板指,0.3396,0.4720,0.5070,0.7746,0.6927,0.5467,-0.1529,0.5632,2016-01-14
SH000688-科创50,0.6323,0.7014,0.8939,0.9475,0.9773,0.7350,-0.8412,-0.2940,2020-07-23
SH000510-中证A500,0.9829,0.9765,0.7521,0.9789,0.9684,0.8297,-0.8825,-0.7542,2024-09-24

,PE_ETF加权,PE_市值加权,PE_等权,PB_ETF加权,PB_市值加权,PB_等权,股息收益率 %,ROE %,最早数据日期
SZ399986-中证银行,0.6704,0.8253,0.3916,0.0003,0.0813,-0.1138,-0.4099,-0.5121,2016-01-14
SZ399975-证券公司,0.1460,0.1486,0.0419,0.7703,0.7968,0.6646,-0.2373,0.4206,2016-01-14
SZ399437-证券龙头,0.1172,0.1586,-0.0216,0.6567,0.7349,0.4908,-0.2803,0.3649,2016-01-14

,PE_ETF加权,PE_市值加权,PE_等权,PB_ETF加权,PB_市值加权,PB_等权,股息收益率 %,ROE %,最早数据日期
SH000932-中证消费,0.6731,0.6451,0.5822,0.8507,0.8485,0.5521,-0.3274,0.4115,2016-01-14
SZ399989-中证医疗,0.2535,0.3475,0.4578,0.8925,0.9039,0.7761,-0.4823,0.6919,2016-01-14
CSI930726-中证生物医药,0.4577,0.5594,0.3217,0.7385,0.8566,0.3885,-0.5053,0.3543,2016-01-14
CSI930641-中证中药,0.4918,0.5746,0.5508,0.6598,0.6611,0.6499,-0.5003,0.2022,2016-01-14
CSI931152-创新药,0.8675,0.5849,0.8773,0.9152,0.9296,0.7007,-0.8425,0.6952,2019-04-23
SH000913-300医药,0.8982,0.9024,0.8249,0.9279,0.9229,0.7578,-0.6538,0.2606,2016-01-14
SH000933-中证医药,0.7619,0.7371,0.6328,0.9145,0.9230,0.6895,-0.7042,0.4702,2016-01-14

,PE_ETF加权,PE_市值加权,PE_等权,PB_ETF加权,PB_市值加权,PB_等权,股息收益率 %,ROE %,最早数据日期
CSI930713-人工智能,0.3013,0.4736,0.1620,0.9536,0.9117,0.5224,-0.3124,0.5210,2016-01-14
CSI000941-新能源,0.2906,0.4684,0.1189,0.9169,0.9285,0.8961,-0.4366,0.5477,2016-01-14
CSIH30184-半导体,0.0626,0.6548,0.6283,0.8672,0.8167,0.7303,-0.6314,0.2650,2016-01-14
SZ399976-CS新能源车,0.1809,0.3819,0.4245,0.7567,0.7482,0.5430,-0.4219,0.1023,2016-01-14
CSIH30590-机器人,0.5058,0.6068,0.6744,0.9253,0.9136,0.7871,-0.6403,0.1587,2016-01-14
CSI931151-光伏产业,0.0847,0.1118,0.3355,0.9438,0.9580,0.9254,-0.5800,0.4617,2019-04-23
CSI931160-通信设备,0.0146,0.2663,0.6868,0.9660,0.9676,0.7570,-0.1443,0.5586,2016-01-14

,PE_ETF加权,PE_市值加权,PE_等权,PB_ETF加权,PB_市值加权,PB_等权,股息收益率 %,ROE %,最早数据日期
SH000928-中证能源,-0.2021,-0.2934,-0.1692,0.6818,0.7580,0.2544,0.3292,0.6975,2016-01-14
CSI930632-CS稀金属,-0.0100,0.0260,-0.3166,0.4890,0.5637,0.2959,-0.2515,0.4647,2016-01-14
SH000819-有色金属,-0.1266,-0.1112,-0.2200,0.7701,0.8583,0.5304,0.1195,0.5287,2016-01-14
CSIH30199-电力指数,0.1028,0.1497,0.0895,0.7366,0.6302,0.3472,-0.3555,0.0758,2016-01-14

,PE_ETF加权,PE_市值加权,PE_等权,PB_ETF加权,PB_市值加权,PB_等权,股息收益率 %,ROE %,最早数据日期
SZ399967-中证军工,0.2500,0.3426,0.4752,0.7126,0.8319,0.6750,0.0271,0.2203,2016-01-14
CSI931066-军工龙头,0.5278,0.4694,0.2965,0.7551,0.8265,0.8272,-0.7027,0.1524,2018-02-05

Empty DataFrame
Columns: [PE_ETF加权, PE_市值加权, PE_等权, PB_ETF加权, PB_市值加权, PB_等权, 股息收益率 %, ROE %, 最早数据日期]
Index: []

In [6]:
kuanji_dim_df = common.get_highest_correlation_dim(kuanji_df)
common.print_title("宽基 - 最相关系数")
display(kuanji_dim_df)

jinrong_dim_df = common.get_highest_correlation_dim(jinrong_df)
common.print_title("证券金融 - 最相关系数")
display(jinrong_dim_df)

mingsheng_dim_df = common.get_highest_correlation_dim(minsheng_df)
common.print_title("消费民生 - 最相关系数")
display(mingsheng_dim_df)

tech_dim_df = common.get_highest_correlation_dim(tech_df)
common.print_title("新科技 - 最相关系数")
display(tech_dim_df)

industry_dim_df = common.get_highest_correlation_dim(industry_df)
common.print_title("基础工业 - 最相关系数")
display(industry_dim_df)

military_dim_df = common.get_highest_correlation_dim(military_df)
common.print_title("国防军工 - 最相关系数")
display(military_dim_df)

hopless_dim_df = common.get_highest_correlation_dim(hopeless_df)
common.print_title("夕阳产业 - 最相关系数")
display(hopless_dim_df)

                    最相关维度   相关系数      最早数据日期
SH000016-上证50    PE_ETF加权 0.7898  2016-01-14
SH000300-沪深300   PE_ETF加权 0.8101  2016-01-14
SZ399006-创业板指    PB_ETF加权 0.7746  2016-01-14
SH000688-科创50     PB_市值加权 0.9773  2020-07-23
SH000510-中证A500  PE_ETF加权 0.9829  2024-09-24

                 最相关维度   相关系数      最早数据日期
SZ399986-中证银行  PE_市值加权 0.8253  2016-01-14
SZ399975-证券公司  PB_市值加权 0.7968  2016-01-14
SZ399437-证券龙头  PB_市值加权 0.7349  2016-01-14

                     最相关维度   相关系数      最早数据日期
SH000932-中证消费     PB_ETF加权 0.8507  2016-01-14
SZ399989-中证医疗      PB_市值加权 0.9039  2016-01-14
CSI930726-中证生物医药   PB_市值加权 0.8566  2016-01-14
CSI930641-中证中药     PB_市值加权 0.6611  2016-01-14
CSI931152-创新药      PB_市值加权 0.9296  2019-04-23
SH000913-300医药    PB_ETF加权 0.9279  2016-01-14
SH000933-中证医药      PB_市值加权 0.9230  2016-01-14

                    最相关维度   相关系数      最早数据日期
CSI930713-人工智能   PB_ETF加权 0.9536  2016-01-14
CSI000941-新能源     PB_市值加权 0.9285  2016-01-14
CSIH30184-半导体    PB_ETF加权 0.8672  2016-01-14
SZ399976-CS新能源车  PB_ETF加权 0.7567  2016-01-14
CSIH30590-机器人    PB_ETF加权 0.9253  2016-01-14
CSI931151-光伏产业    PB_市值加权 0.9580  2019-04-23
CSI931160-通信设备    PB_市值加权 0.9676  2016-01-14

                    最相关维度   相关系数      最早数据日期
SH000928-中证能源     PB_市值加权 0.7580  2016-01-14
CSI930632-CS稀金属   PB_市值加权 0.5637  2016-01-14
SH000819-有色金属     PB_市值加权 0.8583  2016-01-14
CSIH30199-电力指数   PB_ETF加权 0.7366  2016-01-14

                  最相关维度   相关系数      最早数据日期
SZ399967-中证军工   PB_市值加权 0.8319  2016-01-14
CSI931066-军工龙头    PB_等权 0.8272  2018-02-05

Empty DataFrame
Columns: [最相关维度, 相关系数, 最早数据日期]
Index: []

In [7]:
common.print_title("宽基 - 最相关维度百分位%")
display(common.calc_highest_correlation_dim_latest_percentile(
    data_dir, kuanji_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("证券金融 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, jinrong_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("消费民生 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, mingsheng_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("新科技 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, tech_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("基础工业 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, industry_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("国防军工 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, military_dim_df, from_date, date_col_name="日期"
    )
)

common.print_title("夕阳产业 - 最相关维度百分位%")
display(
    common.calc_highest_correlation_dim_latest_percentile(
        data_dir, hopless_dim_df, from_date, date_col_name="日期"
    )
)

                    最相关维度   相关系数      最早数据日期   最新维度值  最新百分位%      最新数据日期
SH000016-上证50    PE_ETF加权 0.7898  2016-01-14 11.4700 69.4041  2026-10-29
SH000300-沪深300   PE_ETF加权 0.8101  2016-01-14 13.9600 55.0038  2026-10-29
SZ399006-创业板指    PB_ETF加权 0.7746  2016-01-14  4.2000 26.0321  2026-10-29
SH000688-科创50     PB_市值加权 0.9773  2020-07-23  5.7600 56.9454  2026-10-29
SH000510-中证A500  PE_ETF加权 0.9829  2024-09-24 16.1700 37.3518  2026-10-29

                 最相关维度   相关系数      最早数据日期  最新维度值  最新百分位%      最新数据日期
SZ399986-中证银行  PE_市值加权 0.8253  2016-01-14 7.8800 99.6154  2026-10-29
SZ399975-证券公司  PB_市值加权 0.7968  2016-01-14 1.0200  2.4231  2026-10-29
SZ399437-证券龙头  PB_市值加权 0.7349  2016-01-14 1.0100  2.7308  2026-10-29

                     最相关维度   相关系数      最早数据日期  最新维度值  最新百分位%      最新数据日期
SH000932-中证消费     PB_ETF加权 0.8507  2016-01-14 3.6800  8.4416  2026-10-29
SZ399989-中证医疗      PB_市值加权 0.9039  2016-01-14 3.2700  8.6154  2026-10-29
CSI930726-中证生物医药   PB_市值加权 0.8566  2016-01-14 4.1700 15.3346  2026-10-29
CSI930641-中证中药     PB_市值加权 0.6611  2016-01-14 1.9600  2.0785  2026-10-29
CSI931152-创新药      PB_市值加权 0.9296  2019-04-23 3.6600 32.5824  2026-10-29
SH000913-300医药    PB_ETF加权 0.9279  2016-01-14 3.2800  4.3545  2026-10-29
SH000933-中证医药      PB_市值加权 0.9230  2016-01-14 2.9200  9.3965  2026-10-29

                    最相关维度   相关系数      最早数据日期  最新维度值  最新百分位%      最新数据日期
CSI930713-人工智能   PB_ETF加权 0.9536  2016-01-14 6.1100 88.4911  2026-10-29
CSI000941-新能源     PB_市值加权 0.9285  2016-01-14 2.0800  7.0814  2026-10-29
CSIH30184-半导体    PB_ETF加权 0.8672  2016-01-14 6.3700 68.3365  2026-10-29
SZ399976-CS新能源车  PB_ETF加权 0.7567  2016-01-14 2.2900  5.4231  2026-10-29
CSIH30590-机器人    PB_ETF加权 0.9253  2016-01-14 3.9000 57.1594  2026-10-29
CSI931151-光伏产业    PB_市值加权 0.9580  2019-04-23 1.6000  3.7912  2026-10-29
CSI931160-通信设备    PB_市值加权 0.9676  2016-01-14 5.9000 89.6750  2026-10-29

                    最相关维度   相关系数      最早数据日期  最新维度值  最新百分位%      最新数据日期
SH000928-中证能源     PB_市值加权 0.7580  2016-01-14 1.5600 98.5867  2026-10-29
CSI930632-CS稀金属   PB_市值加权 0.5637  2016-01-14 2.7000 23.4411  2026-10-29
SH000819-有色金属     PB_市值加权 0.8583  2016-01-14 2.6000 64.1923  2026-10-29
CSIH30199-电力指数   PB_ETF加权 0.7366  2016-01-14 1.5500 54.4650  2026-10-29

                  最相关维度   相关系数      最早数据日期  最新维度值  最新百分位%      最新数据日期
SZ399967-中证军工   PB_市值加权 0.8319  2016-01-14 2.9600 33.6134  2026-10-29
CSI931066-军工龙头    PB_等权 0.8272  2018-02-05 2.6600  4.3087  2026-10-29

Empty DataFrame
Columns: [最相关维度, 相关系数, 最早数据日期, 最新维度值, 最新百分位%, 最新数据日期]
Index: []